name: flutter_parental_control_example
description: "Demonstrates how to use the flutter_parental_control plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_parental_control:
    path: ../
  cupertino_icons: ^1.0.8
  realm: ^20.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
